<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RunicCore.Tests</AssemblyName>
    <RootNamespace>Runic.Foundation.Core.Tests</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Api\*.cs" Link="Api\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
