<Project><Target Name="SentinelMergeYaml" AfterTargets="Build" Condition="'$(Configuration)'=='Release'"><ItemGroup><SentinelMergeInput Include="$(IntermediateOutputPath)$(TargetFileName)" /><SentinelMergeInput Include="$(TargetDir)YamlDotNet.dll" /></ItemGroup><ILRepack Parallel="false" DebugInfo="false" Internalize="true" InputAssemblies="@(SentinelMergeInput)" OutputFile="$(TargetPath)" TargetKind="SameAsPrimaryAssembly" LibraryPath="$(TargetDir);$(GAME_MANAGED);$(BEPINEX_PROFILE)/core" /></Target></Project>