<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\ClockView.cs" Link="Production\ClockView.cs" />
    <Compile Include="..\..\ClockModel.cs" Link="Production\ClockModel.cs" />
  </ItemGroup>
</Project>
