<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>ArcaneDecorWaterGardens</AssemblyName>
    <RootNamespace>RunicLilyPads</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <VALHEIM_INSTALL Condition="'$(VALHEIM_INSTALL)' == ''">E:\SteamLibrary\steamapps\common\Valheim</VALHEIM_INSTALL>
    <GAME_MANAGED>$(VALHEIM_INSTALL)\valheim_Data\Managed</GAME_MANAGED>
    <BEPINEX_PROFILE Condition="'$(BEPINEX_PROFILE)' == ''">C:\Users\Charles Sammons\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Solo\BepInEx</BEPINEX_PROFILE>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Audio/night_ambience_*.wav" LogicalName="WaterGardens.Audio.%(Filename)%(Extension)" />
    <Compile Remove="Tests/**/*.cs" />
    <Compile Remove="StoneLantern.cs" />
    <Compile Remove="LanternAssetProject/**/*.cs" />
    <Compile Remove="CascadeAssetProject/**/*.cs" />
    <EmbeddedResource Include="Assets/GardenModels/*.meshbin;Assets/GardenModels/*.jpg;Assets/GardenModels/*.png" LogicalName="WaterGardens.Models.%(Filename)%(Extension)" />
    <EmbeddedResource Remove="Assets/GardenModels/fern_002_alt.*;Assets/GardenModels/fountain_003.*;Assets/GardenModels/fountain_003_emission.png" />
    <EmbeddedResource Include="Assets/Waterfall/watergardens_cascade" LogicalName="WaterGardens.Cascade" />
    <EmbeddedResource Include="Audio/waterfall_001.wav" LogicalName="WaterGardens.Audio.waterfall_001.wav" />
    <EmbeddedResource Include="Audio/waterfall_002.wav" LogicalName="WaterGardens.Audio.waterfall_002.wav" />
    <EmbeddedResource Include="Audio/fountain_001.wav" LogicalName="WaterGardens.Audio.fountain_001.wav" />
    <Reference Include="UnityEngine.UIModule" HintPath="$(GAME_MANAGED)\UnityEngine.UIModule.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="$(GAME_MANAGED)\UnityEngine.UI.dll" Private="false" />
    <Reference Include="UnityEngine.AudioModule" HintPath="$(GAME_MANAGED)\UnityEngine.AudioModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(GAME_MANAGED)\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(GAME_MANAGED)\UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="BepInEx" HintPath="$(BEPINEX_PROFILE)\core\BepInEx.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(BEPINEX_PROFILE)\core\0Harmony.dll" Private="false" />
    <Reference Include="Jotunn" HintPath="$(BEPINEX_PROFILE)\plugins\ValheimModding-Jotunn\Jotunn.dll" Private="false" />
    <Reference Include="assembly_valheim" HintPath="$(GAME_MANAGED)\assembly_valheim.dll" Private="false" />
    <Reference Include="assembly_utils" HintPath="$(GAME_MANAGED)\assembly_utils.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(GAME_MANAGED)\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(GAME_MANAGED)\UnityEngine.AssetBundleModule.dll" Private="false" />
    <Reference Include="UnityEngine.AnimationModule" HintPath="$(GAME_MANAGED)\UnityEngine.AnimationModule.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(GAME_MANAGED)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(GAME_MANAGED)\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="UnityEngine.PhysicsModule" HintPath="$(GAME_MANAGED)\UnityEngine.PhysicsModule.dll" Private="false" />
    <Reference Include="UnityEngine.ScreenCaptureModule" HintPath="$(GAME_MANAGED)\UnityEngine.ScreenCaptureModule.dll" Private="false" />
    <Reference Include="UnityEngine.ParticleSystemModule" HintPath="$(GAME_MANAGED)\UnityEngine.ParticleSystemModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(GAME_MANAGED)\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="Unity.TextMeshPro" HintPath="$(GAME_MANAGED)\Unity.TextMeshPro.dll" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="assembly_guiutils" HintPath="$(GAME_MANAGED)\assembly_guiutils.dll" Private="false" />
    <Compile Include="../Shared/Localization/*.cs" Link="Localization/%(Filename)%(Extension)" />
    <EmbeddedResource Include="Translations/ArcaneDecorWaterGardens/English.json" LogicalName="Runic.Localization.English.json" />
    <None Update="Translations/**/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>

